# === [ GENERAL CONFIG ] ===
root = "."
tmp_dir = "tmp"

# === [ BUILD CONFIG ] ===
[build]
cmd = "go build -o ./tmp/main.exe cmd/api/main.go"
bin = "./tmp/main.exe"
delay = 1000 # ms
exclude_dir = ["assets", "tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html", "json"]
exclude_regex = ["_test\\.go"]

# === [ WATCH CONFIG ] ===
[watch]
include_ext = ["go", "env", "tpl", "tmpl", "html", "css", "js"]
include_dir = ["."]
exclude_dir = ["tmp", "vendor", "node_modules", "logs"]
exclude_file = ["**/*_test.go"]

# === [ LOGGING CONFIG ] ===
[log]
time = true
color = true
level = "debug"

# === [ ENV CONFIG ] ===
[env]
# POSTGRES
DB_USER="developer"
DB_PASSWORD="developerganteng"
DB_HOST="localhost"
DB_PORT=5432
DB_NAME="neliquiz_dev"
DB_SSLMODE="disable"
DB_MAX_IDLE_CONN=10
DB_MAX_OPEN_CONN=100
DB_MAX_CONN_LIFETIME=300

# WEBSERVER
HTTP_HOST="localhost"
HTTP_PORT=3000
HTTP_PREFORK=false