# === [ GENERAL CONFIG ] ===
root = "."
tmp_dir = "tmp"

# === [ BUILD CONFIG ] ===
[build]
cmd = "go build -o ./tmp/main.exe cmd/api/main.go"
bin = "./tmp/main.exe"
delay = 1000 # ms
exclude_dir = ["assets", "tmp", "vendor"]
include_ext = ["go", "tpl", "tmpl", "html", "json"]
exclude_regex = ["_test\\.go"]

# === [ WATCH CONFIG ] ===
[watch]
include_ext = ["go", "env", "tpl", "tmpl", "html", "css", "js"]
include_dir = ["."]
exclude_dir = ["tmp", "vendor", "node_modules", "logs"]
exclude_file = ["**/*_test.go"]

# === [ LOGGING CONFIG ] ===
[log]
time = true
color = true
level = "debug"
