name: Deploy to EC2 via Git + Podman (on PR merge from develop)

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'develop'
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/app
            git fetch origin main
            git reset --hard origin/main

            cat > .env <<EOL
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_PORT=${{ secrets.DB_PORT }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_SSLMODE=${{ secrets.DB_SSLMODE }}
            HTTP_HOST=${{ vars.HTTP_HOST }}
            HTTP_PORT=${{ vars.HTTP_PORT }}
            HTTP_PREFORK=${{ vars.HTTP_PREFORK }}
            HTTP_DEBUG=${{ vars.HTTP_DEBUG }}
            GAME_HOST=${{ vars.GAME_HOST }}
            GAME_PORT=${{ vars.GAME_PORT }}
            GAME_DEBUG=${{ vars.GAME_DEBUG }}
            VALIDATE_API_GATEWAY=${{ vars.VALIDATE_API_GATEWAY }}
            API_GATEWAY_TOKEN=${{ vars.API_GATEWAY_TOKEN }}
            EOL

            podman compose -f build --no-cache
            podman compose up -d --remove-orphans
