name: Deploy to EC2 via Git + Podman (on PR merge from develop)

on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.head.ref == 'develop'
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: SSH and deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            set -e
            
            git config --global --add safe.directory /home/${USER}/app
            
            cd ~/app
            git fetch origin main
            git reset --hard origin/main

            # Hapus image lama untuk jamin build fresh
            podman stop neliquiz || true
            podman rm neliquiz || true
            podman rmi neliquiz:latest || true

            # Build image tanpa cache
            podman build --no-cache -t neliquiz:latest .

            podman run -d --name neliquiz -p 5080:${{ vars.HTTP_PORT }} \
              -e DB_HOST='${{ secrets.DB_HOST }}' \
              -e DB_NAME='${{ secrets.DB_NAME }}' \
              -e DB_PASSWORD='${{ secrets.DB_PASSWORD }}' \
              -e DB_PORT='${{ secrets.DB_PORT }}' \
              -e DB_USER='${{ secrets.DB_USER }}' \
              -e DB_SSLMODE='${{ secrets.DB_SSLMODE }}' \
              -e HTTP_HOST='${{ vars.HTTP_HOST }}' \
              -e HTTP_PORT='${{ vars.HTTP_PORT }}' \
              -e HTTP_PREFORK='${{ vars.HTTP_PREFORK }}' \
              -e VALIDATE_API_GATEWAY='${{ vars.VALIDATE_API_GATEWAY }}' \
              -e API_GATEWAY_TOKEN='${{ vars.API_GATEWAY_TOKEN }}' \
              neliquiz:latest
